from dagster import StaticPartitionsDefinition

telephony_providers = StaticPartitionsDefinition(
    ["AVANTEL S.A.S"
    , "UFF MOVIL SAS"
    , "INVERSIONES AMAPA S.A.S."
    , "COLOMBIA TELECOMUNICACIONES S.A. E.S.P."
    , "EMPRESA COLOMBIANA DE PROCESOS TECNOLOGICOS, TECNOLOGIA Y COMUNICACIONES S.A."
    , "SETROC MOBILE GROUP SAS"
    , "EMPRESA DE TELECOMUNICACIONES DE BOGOTA S.A. ESP"
    , "LOV TELECOMUNICACIONES SAS"
    , "UNE EPM TELECOMUNICACIONES S.A."
    , "COMUNICACION CELULAR S A COMCEL S A"
    , "COLOMBIA MOVIL  S.A ESP"
    , "PARTNERS TELECOM COLOMBIA SAS"
    , "LOGISTICA FLASH COLOMBIA S.A.S"
    , "VIRGIN MOBILE COLOMBIA S.A.S."
    , "SUMA MOVIL S.A.S."
    , "ALMACENES EXITO INVERSIONES S.A.S."
    , "LIWA SAS ESP"
    , "MERCANET SAS"]
)